apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: tapps.apps.tkestack.io
spec:
  group: apps.tkestack.io
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                replicas:
                  type: integer
      subresources:
        status: {}
        scale:
          labelSelectorPath: .status.scaleLabelSelector
          specReplicasPath: .spec.replicas
          statusReplicasPath: .status.replicas
  names:
    kind: TApp
    listKind: TAppList
    plural: tapps
    singular: tapp
    shortNames:
      - tp
  scope: Namespaced