apiVersion: v1
kind: Config
clusters:
  - cluster:
      certificate-authority-data: xxx
      server: https://xxx:6443
    name: cluster1
  - cluster:
      certificate-authority-data: xxx
      server: https://xxx:6443
    name: cluster2
contexts:
  - context:
      cluster: cluster1
      user: kubelet
    name: cluster1-context
  - context:
      cluster: cluster2
      user: kubelet
    name: cluster2-context
current-context: cluster1-context
preferences: {}
users:
  - name: kubelet
    user:
      client-certificate-data: xxx
      client-key-data: xxx