apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: default
  name: pod-controller-role
rules:
  - apiGroups: [""] # "" indicates the core API group
    resources: ["services"]
    verbs: ["list", "watch"]
  - apiGroups: ["networking.k8s.io"]
    resources: ["ingresses"]
    verbs: ["list", "watch", "create", "update", "delete"]
