apiVersion: apps/v1
kind: Deployment
metadata:
  name: admission-webhook-base-deployment
  labels:
    app: admission-webhook-base
spec:
  replicas: 1
  selector:
    matchLabels:
      app: admission-webhook-base
  template:
    metadata:
      labels:
        app: admission-webhook-base
    spec:
      serviceAccount: admission-webhook-base-sa
      containers:
        - name: admission-webhook-base
          image: librant/admission-webhook-base:v1.0.0
          imagePullPolicy: Always
          args:
            - -tlsCertFile=/etc/webhook/certs/cert.pem
            - -tlsKeyFile=/etc/webhook/certs/key.pem
            - -alsologtostderr
            - -v=4
            - 2>&1
          volumeMounts:
            - name: webhook-certs
              mountPath: /etc/webhook/certs
              readOnly: true
      volumes:
        - name: webhook-certs
          secret:
            secretName: admission-webhook-base-certs