apiVersion: v1
kind: ServiceAccount
metadata:
  name: admission-webhook-base-sa
  labels:
    app: admission-webhook-base

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: admission-webhook-base-cr
  labels:
    app: admission-webhook-base
rules:
  - apiGroups:
      - librant.com
    resources:
      - "*"
    verbs:
      - "*"
  - apiGroups:
      - ""
    resources:
      - pods
      - events
    verbs:
      - "*"
  - apiGroups:
      - apps
    resources:
      - deployments
      - daemonsets
      - replicasets
      - statefulsets
    verbs:
      - "*"
  - apiGroups:
      - autoscaling
    resources:
      - '*'
    verbs:
      - '*'

---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: admission-webhook-base-crb
  labels:
    app: admission-webhook-base
subjects:
  - kind: ServiceAccount
    name: admission-webhook-base-sa
    namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: admission-webhook-base-cr