apiVersion: v1
kind: Service
metadata:
  name: admission-webhook-base-svc
  labels:
    app: admission-webhook-base
spec:
  ports:
    - port: 443
      targetPort: 443
  selector:
    app: admission-webhook-base