apiVersion: apiextensions.k8s.io/v1beta1
  kind: CustomResourceDefinition
  metadata:
    name: crontabs.stable.example.com
  spec:
    group: stable.example.com
    version: v1
    scope: Namespaced
    names:
      plural: crontabs
      singular: crontab
      kind: CronTab
      shortNames:
        - ct
    additionalPrinterColumns:
      - name: Spec
        type: string
        description: The cron spec defining the interval a CronJob is run
        JSONPath: .spec.cronSpec
      - name: Replicas
        type: integer
        description: The number of jobs launched by the CronJob
        JSONPath: .spec.replicas
      - name: Age
        type: date
        JSONPath: .metadata.creationTimestamp